import enum


class UserRole(str, enum.Enum):
    MAINTENANCE_STAFF = "MAINTENANCE_STAFF"
    JUNIOR_ENGINEER = "JUNIOR_ENGINEER"
    SENIOR_SECTION_ENGINEER = "SENIOR_SECTION_ENGINEER"
    OPERATOR = "OPERATOR"
    CONTROLLER = "CONTROLLER"
    AUTHORIZED_OFFICIAL = "AUTHORIZED_OFFICIAL"
    EMERGENCY_OPERATOR = "EMERGENCY_OPERATOR"


class SeverityLevel(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class NotificationPriority(str, enum.Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class MaintenanceRequestStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    PENDING = "PENDING"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    BLOCK_PLANNING = "BLOCK_PLANNING"
    AI_RECOMMENDATION = "AI_RECOMMENDATION"
    OFFICIAL_REVIEW = "OFFICIAL_REVIEW"
    APPROVED = "APPROVED"
    MODIFIED = "MODIFIED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"


class BlockRequestStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class OptimizedBlockStatus(str, enum.Enum):
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    SCHEDULED = "SCHEDULED"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
    ACTIVE = "ACTIVE"
    MAINTENANCE = "MAINTENANCE"
    CLEARANCE_PENDING = "CLEARANCE_PENDING"
    RELEASED = "RELEASED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class IntegrationResponse(str, enum.Enum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    MODIFY = "MODIFY"


class IntegrationFinalStatus(str, enum.Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"
    APPROVED = "APPROVED"


class IncidentType(str, enum.Enum):
    TRACK_FAILURE = "TRACK_FAILURE"
    TRACK_OBSTRUCTION = "TRACK_OBSTRUCTION"
    SIGNAL_FAILURE = "SIGNAL_FAILURE"
    OHE_TRACTION_FAILURE = "OHE_TRACTION_FAILURE"
    ELECTRICAL_FAILURE = "ELECTRICAL_FAILURE"
    EQUIPMENT_FAILURE = "EQUIPMENT_FAILURE"
    ACCIDENT = "ACCIDENT"
    DERAILMENT_RELATED = "DERAILMENT_RELATED"
    DERAILMENT_RELATED_INFRASTRUCTURE_ISSUE = "DERAILMENT_RELATED_INFRASTRUCTURE_ISSUE"
    PERSON_ON_TRACK = "PERSON_ON_TRACK"
    FIRE_OR_HAZARD = "FIRE_OR_HAZARD"
    FLOOD = "FLOOD"
    WEATHER_RELATED_RISK = "WEATHER_RELATED_RISK"
    BRIDGE_OR_STRUCTURE_ISSUE = "BRIDGE_OR_STRUCTURE_ISSUE"
    OTHER = "OTHER"
    OTHER_EMERGENCY = "OTHER_EMERGENCY"


class IncidentStatus(str, enum.Enum):
    REPORTED = "REPORTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    ASSESSED = "ASSESSED"
    EMERGENCY_PLANNING = "EMERGENCY_PLANNING"
    AWAITING_OFFICIAL_DECISION = "AWAITING_OFFICIAL_DECISION"
    APPROVED = "APPROVED"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
    RESPONSE_DISPATCHED = "RESPONSE_DISPATCHED"
    ON_SITE = "ON_SITE"
    WORK_IN_PROGRESS = "WORK_IN_PROGRESS"
    CLEARANCE_PENDING = "CLEARANCE_PENDING"
    CLEARED = "CLEARED"
    INCIDENT_CLOSED = "INCIDENT_CLOSED"


class IncidentResponseStatus(str, enum.Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    CLEARED = "CLEARED"


class EmergencyResponseStatus(str, enum.Enum):
    ALERT_RECEIVED = "ALERT_RECEIVED"
    TEAM_DISPATCHED = "TEAM_DISPATCHED"
    TEAM_ARRIVED = "TEAM_ARRIVED"
    ON_SITE = "ON_SITE"
    WORK_IN_PROGRESS = "WORK_IN_PROGRESS"
    CLEARANCE_PENDING = "CLEARANCE_PENDING"
    INCIDENT_HANDED_OVER = "INCIDENT_HANDED_OVER"
    AREA_CLEARED = "AREA_CLEARED"
    CLEARED = "CLEARED"
    CLOSED = "CLOSED"


class NotificationType(str, enum.Enum):
    NEW_MAINTENANCE_REQUEST = "NEW_MAINTENANCE_REQUEST"
    REQUEST_VERIFICATION = "REQUEST_VERIFICATION"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    BLOCK_INTEGRATION_OPPORTUNITY = "BLOCK_INTEGRATION_OPPORTUNITY"
    INTEGRATION_ACCEPTED = "INTEGRATION_ACCEPTED"
    INTEGRATION_REJECTED = "INTEGRATION_REJECTED"
    AI_RECOMMENDATION_READY = "AI_RECOMMENDATION_READY"
    OFFICIAL_APPROVAL_REQUIRED = "OFFICIAL_APPROVAL_REQUIRED"
    BLOCK_APPROVED = "BLOCK_APPROVED"
    BLOCK_MODIFIED = "BLOCK_MODIFIED"
    BLOCK_REJECTED = "BLOCK_REJECTED"
    EMERGENCY_ALERT = "EMERGENCY_ALERT"
    EMERGENCY_REPLANNING = "EMERGENCY_REPLANNING"
