import enum


class UserRole(str, enum.Enum):
    MAINTENANCE_STAFF = "MAINTENANCE_STAFF"
    ENGINEER_REVIEWER = "ENGINEER_REVIEWER"
    OPERATOR = "OPERATOR"
    CONTROLLER = "CONTROLLER"
    AUTHORIZED_OFFICIAL = "AUTHORIZED_OFFICIAL"
    EMERGENCY_OPERATOR = "EMERGENCY_OPERATOR"


class SeverityLevel(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class NotificationPriority(str, enum.Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class MaintenanceRequestStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    PENDING = "PENDING"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    BLOCK_PLANNING = "BLOCK_PLANNING"
    AI_RECOMMENDATION = "AI_RECOMMENDATION"
    OFFICIAL_REVIEW = "OFFICIAL_REVIEW"
    APPROVED = "APPROVED"
    MODIFIED = "MODIFIED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"


class BlockRequestStatus(str, enum.Enum):
    REQUESTED = "REQUESTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class OptimizedBlockStatus(str, enum.Enum):
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class IntegrationResponse(str, enum.Enum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    MODIFY = "MODIFY"


class IntegrationFinalStatus(str, enum.Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"
    APPROVED = "APPROVED"


class IncidentType(str, enum.Enum):
    ACCIDENT = "ACCIDENT"
    DERAILMENT_RELATED = "DERAILMENT_RELATED"
    TRACK_FAILURE = "TRACK_FAILURE"
    SIGNAL_FAILURE = "SIGNAL_FAILURE"
    OHE_FAILURE = "OHE_FAILURE"
    OBSTRUCTION = "OBSTRUCTION"
    PERSON_ON_TRACK = "PERSON_ON_TRACK"
    SUSPECTED_SUICIDE = "SUSPECTED_SUICIDE"
    OTHER_EMERGENCY = "OTHER_EMERGENCY"


class IncidentResponseStatus(str, enum.Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    CLEARED = "CLEARED"


class EmergencyResponseStatus(str, enum.Enum):
    ALERT_RECEIVED = "ALERT_RECEIVED"
    TEAM_DISPATCHED = "TEAM_DISPATCHED"
    TEAM_ARRIVED = "TEAM_ARRIVED"
    INCIDENT_HANDED_OVER = "INCIDENT_HANDED_OVER"
    AREA_CLEARED = "AREA_CLEARED"


class NotificationType(str, enum.Enum):
    NEW_MAINTENANCE_REQUEST = "NEW_MAINTENANCE_REQUEST"
    REQUEST_VERIFICATION = "REQUEST_VERIFICATION"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    BLOCK_INTEGRATION_OPPORTUNITY = "BLOCK_INTEGRATION_OPPORTUNITY"
    INTEGRATION_ACCEPTED = "INTEGRATION_ACCEPTED"
    INTEGRATION_REJECTED = "INTEGRATION_REJECTED"
    AI_RECOMMENDATION_READY = "AI_RECOMMENDATION_READY"
    OFFICIAL_APPROVAL_REQUIRED = "OFFICIAL_APPROVAL_REQUIRED"
    BLOCK_APPROVED = "BLOCK_APPROVED"
    BLOCK_MODIFIED = "BLOCK_MODIFIED"
    BLOCK_REJECTED = "BLOCK_REJECTED"
    EMERGENCY_ALERT = "EMERGENCY_ALERT"
    EMERGENCY_REPLANNING = "EMERGENCY_REPLANNING"
